name: Audit Data Repository
on:
  push:
    branches:
      - 'main'
jobs:
  book-keeping:
    if: github.repository == 'uva-bi-sdad/sdc.broadband_dev'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "💡 The ${{ github.repository }} repository have been cloned to the runner."
      - name: Check out auditor repository code
        uses: actions/checkout@master
        with:
          repository: uva-bi-sdad/auditor
          path: auditor/
      - run: echo "🌝 The repo is now cloned on the runner"
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository (Useful for debugging)
        run: |
          ls -la ${{ github.workspace }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6 #install the python needed
      - name: Install requirements
        run: |
          pip install -r auditor/requirements.txt
      - name: Execute python script # create a manifest with the current directory as root
        run: |
          python auditor/audit.py -i .
      # - name: update the yml file to the newest version on the auditor repo (requires permissions )
      #   run: |
      #     cp sdad_data-auditor/runner.yml .github/workflows/runner.yml
      - name: Remove auditor files
        run: |
          rm -rf auditor
      - name: Commit the results
        run: |
          git config --local user.name "robot"
          git add .
          git commit -m "Automated manifest update"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: List current working directory
        run: |
          ls -la          
      - name: Remove all files that do not have a distribution in its path, ignoring all files in root
        run: |
          find ${{ github.workspace }} -mindepth 2 -type f ! -wholename "**/distribution/*" -delete
      - name: Remove github things # Required so that you can push to another directory
        run: |
          rm -rf .git
      - name: Print working directory
        run: |
          pwd
      - name: List current working directory
        run: |
          ls -la
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: 'uva-bi-sdad'
          destination-repository-name: 'sdc.broadband'
          target-branch: main
      - run: echo "🍏 This job's status is ${{ job.status }}."
      

